global using Microsoft.EntityFrameworkCore;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using PerfumeShop.Infrastructure.DataAccess.DbContexts;
global using PerfumeShop.Core.Interfaces;
global using Microsoft.EntityFrameworkCore.Query;
global using System.Linq.Expressions;
global using PerfumeShop.Core.Models.Entities;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;