global using Microsoft.AspNetCore.Mvc;
global using PerfumeShop.Models;
global using System.Diagnostics;
global using PerfumeShop.Web.Configurations;
global using PerfumeShop.Infrastructure.DataAccess;
global using PerfumeShop.Core.Interfaces;
global using PerfumeShop.Infrastructure.DataAccess.Repository;
global using Serilog;
global using PerfumeShop.Core.Models.Entities;